/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rbs.transformer;
import py4j.GatewayServer;
import rbs.transformer.EvaluationTruss;

public class App {
    public static void main(String[] args) {
        EvaluationTruss myJavaObject = new EvaluationTruss();
        py4j.GatewayServer gatewayServer = new py4j.GatewayServer(myJavaObject);
        gatewayServer.start();
        System.out.println("Gateway Server Started");
    }
}